spring:
  data:
    rest:
      base-path: /api
    mongodb:
      host: localhost
      port: 27017
      database: burgercloud
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: burgercloud-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.bassmeister.burgercloud.domain
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  webflux:
    base-path: /api
burgercloud:
  email:
    host: imap.abc.com
    mailbox: INBOX
    username: burger-in-flow
    password: 1L0v3BURg3Rs
    poll-rate: 10000
