spring:
  datasource:
    url: jdbc:h2:mem:default
  h2:
    console:
      enabled: true
      path: /h2console/
  data:
    rest:
      base-path: /api
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: burgercloud-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.bassmeister.burgercloud.domain
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
burgercloud:
  email:
    host: imap.gmail.com
    mailbox: INBOX
    username: burger-in-flow
    password: 1L0v3BURg3Rs
    poll-rate: 10000